/**
 * @file encoder_motor.c
 * @author Lu Yongping
 * @brief Encoder motor hardware-independent code
 * @version 0.1
 * @date 2023-07-12
 *
 * @copyright Copyright (c) 2023
 *
 */

#include "encoder_motor.h"
#include "gpio.h"

/**
 * @brief Encoder motor speed measurement update
 * @details
 * @param self Pointer to the encoder motor object
 * @param period Time interval since the last update (update period), in seconds
 * @param counter Current encoder count value
 * @retval None.
 */
void encoder_update(EncoderMotorObjectTypeDef *self, float period, int64_t counter)
{
    counter = counter + self->overflow_num * self->ticks_overflow; /* Total count value, 60000 based on the actual timer overflow value */
    int delta_count = counter - self->counter;
    self->counter = counter; /* Store the new count value */
    self->tps = (float)delta_count / period * 0.9f + self->tps * 0.1f; /* Calculate pulse frequency */
    self->rps = self->tps / self->ticks_per_circle; /* Calculate speed in rps (revolutions per second) */
}

/**
 * @brief Encoder motor speed control task
 * @details Encoder motor speed PID control task, needs to be specified periodically to complete PID control update
 * @param self Pointer to the encoder motor object
 * @param period Time interval since the last update (update period), in seconds
 * @retval None.
 */
void encoder_motor_control(EncoderMotorObjectTypeDef *self, float period)
{
    float pulse = 0;
    pid_controller_update(&self->pid_controller, self->rps, period);   /* Update PID controller */
    pulse = self->current_pulse + self->pid_controller.output; /* Calculate new PWM value */

    /* Limit the output PWM value, the limit is determined according to the timer settings, in this example the timer is set to a duty cycle of 0-100 corresponding to 0-1000 */
    pulse = pulse > 1000 ?  1000 : pulse;
    pulse = pulse < -1000 ? -1000 : pulse;

    self->set_pulse(self, pulse > -250 && pulse < 250 ? 0 : pulse); /* Set the new PWM value and limit the minimum PWM value, if the PWM is too small the motor will only buzz and not move */
    self->current_pulse = pulse; /* Record the new PWM value */
}

/**
 * @brief Set PID control target speed for the encoder motor
 * @param self Pointer to the encoder motor object
 * @param rps Target speed, in revolutions per second
 * @retval None.
 */
void encoder_motor_set_speed(EncoderMotorObjectTypeDef *self, float rps)
{
    rps = rps > self->rps_limit ? self->rps_limit : (rps < -self->rps_limit ? -self->rps_limit : rps); /* Limit the speed */
    self->pid_controller.set_point = rps; /* Set the PID controller target */
}

/**
 * @brief Initialize the encoder motor object
 * @param self Pointer to the encoder motor object
 * @retval None.
 */
void encoder_motor_object_init(EncoderMotorObjectTypeDef *self)
{
    // Reset total count value, overflow count, counter frequency, output shaft speed, current PWM value, and count overflow value
    // Set PID controller target value and the number of counts generated by one rotation of the output shaft to 9999
    self->counter = 0;  
    self->overflow_num = 0;
    self->tps = 0;
    self->rps = 0;
    self->current_pulse = 0;
    self->ticks_overflow = 0;
    self->ticks_per_circle = 9999; /* Number of counts generated by one rotation of the motor output shaft, fill in according to the actual motor situation */
    pid_controller_init(&self->pid_controller, 0, 0, 0);
}
