/**
 *@file encoder_motor.h
 *@author Lu Yongping (Lucas@hiwonder.com)
 *@brief encoder motor control header file
 *@version 0.1
 *@date 2023-05-12
 *
 *@copyright Copyright (c) 2023
 *
 */

#ifndef __ENCODER_MOTOR_H_
#define __ENCODER_MOTOR_H_

#include <stdint.h>
#include "pid.h"

typedef struct EncoderMotorObject EncoderMotorObjectTypeDef;

/**
 *@brief encoder motor object structure
*/
struct EncoderMotorObject{
    int64_t counter;/**< @brief total count value, 64bit thinks that it will not overflow */
    int64_t overflow_num;/**< @brief Overflow Count */
    int32_t ticks_overflow;/**< @brief Count overflow value */
    float tps;/**< @brief ticks per second counter frequency */
    float rps;/**< @brief revolutions per second Output shaft speed rotation per second */
    int current_pulse;/**< @brief The current output PWM value, signed corresponds to forward and reverse */
    PID_ControllerTypeDef pid_controller;/**< @brief PID controller */

/**porting portable hardware interface **/
    int32_t ticks_per_circle;/**< @brief The count number generated by rotating the motor output shaft by one turn, fill in according to the actual situation of the motor */
	float rps_limit;/**< @brief The motor ground speed limit is generally taken at a slightly smaller value than 100% PWM duty cycle to ensure the PID controller's speed control */
/**
      *@brief Set motor speed -1000 ~ 1000
      *@param self encoder motor object
      *@param pulse New PWM value, -1000~1000, corresponding to forward and reverse rotation 0~100% speed
      *@retval None.
      */
    void (*set_pulse)(EncoderMotorObjectTypeDef *self, int pulse);
};


/**
 *@breif Encoder motor object initialization
 *@param self encoder motor object pointer
 *@retval None.
*/
void encoder_motor_object_init(EncoderMotorObjectTypeDef *self);


/**
 *@brief Encoder Motor Speed ​​Measurement Update
 *@detials
 *@param self encoder motor object
 *@param period The interval between this call and the last call is in seconds
 *@param counter The encoder current count value
 *@retval None.
*/
void encoder_update(EncoderMotorObjectTypeDef *self, float period, int64_t new_counter);


/**
 *@brief encoder motor speed control task
 *@detials Encoder motor speed PID control task, requiring regular specification to complete PID control update
 *@param self encoder motor object
 *@param period The interval from the current update to the last update (update period), unit sec
 *@retval None.
*/
void encoder_motor_control(EncoderMotorObjectTypeDef *self, float period);


/**
 *@brief encoder motor sets PID to control target speed
 *@param rps Target speed, unit rotation per second
 *@retval None.
*/
void encoder_motor_set_speed(EncoderMotorObjectTypeDef *self, float rps);

#endif

