@echo off

REM recursively clears files generated by Keil compile

REM Get the current directory
set CURRENT_DIR=%CD%

REM Keil compiled files
echo Deleting output files...
for /r "%CURRENT_DIR%" %%F in (*.o *.obj *.d *.hex *.bin *.axf *.map *.crf *.htm *.lnp *.iex *.dep *.sct *.uvguix.* *.lst) do (
    echo Deleting "%%F"...
    del /q "%%F"
)

echo Cleanup complete.
choice /t 1 /d y /n >nul